version: 2
jobs:
  unittest:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/ziru/openmock
    steps:
      - checkout
      - run: make test

workflows:
  version: 2
  test:
    jobs:
      - unittest
